plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.10'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'com.cdpjenkins'
version '1.01-SNAPSHOT'

repositories {
    mavenCentral()
}

apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'java'

sourceSets {
    intTest {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.12.+"
    implementation 'org.apache.xmlgraphics:batik-all:1.19'

    implementation platform("org.http4k:http4k-bom:6.15.1.0")
    implementation "org.http4k:http4k-core"
    implementation "org.http4k:http4k-format-jackson"
    implementation "org.http4k:http4k-server-netty"
    implementation "org.http4k:http4k-client-okhttp"
    implementation "org.http4k:http4k-config"

    implementation "org.jdbi:jdbi3-bom:3.20.0"
    implementation "org.jdbi:jdbi3-core"
    implementation "org.jdbi:jdbi3-postgres:3.20.0"
    runtimeOnly "org.postgresql:postgresql:42.2.20"

    implementation 'io.github.oshai:kotlin-logging-jvm:5.1.0'
    implementation 'ch.qos.logback:logback-classic:1.5.13'

    implementation platform("software.amazon.awssdk:bom:2.15.15")
    implementation "software.amazon.awssdk:s3"

    implementation("com.github.ajalt.clikt:clikt:5.0.1")
    // implementation("com.github.ajalt.clikt:clikt-markdown:5.0.1")

    testImplementation(platform("org.junit:junit-bom:5.7.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation('com.natpryce:hamkrest:1.8.0.1')

    intTestImplementation(platform("org.junit:junit-bom:5.7.1"))
    intTestImplementation("org.junit.jupiter:junit-jupiter")
    intTestImplementation('com.natpryce:hamkrest:1.8.0.1')

    intTestImplementation "org.testcontainers:testcontainers:1.21.3"
    intTestImplementation "org.testcontainers:junit-jupiter:1.15.3"
    intTestImplementation "org.testcontainers:postgresql:1.15.3"

    intTestRuntimeOnly 'org.postgresql:postgresql:42.7.7'
}


tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}


build {
    dependsOn shadowJar
}
task stage(dependsOn: ['build'])

configurations {
    intTestImplementation.extendsFrom implementation
    intTestRuntimeOnly.extendsFrom runtimeOnly
}

task intTest(type: Test) {
    testClassesDirs = sourceSets.intTest.output.classesDirs
    classpath = sourceSets.intTest.runtimeClasspath

    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}
